### NumPy Cheatsheet

NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

#### 1. Importing NumPy

In [1]:
import numpy as np

#### 2. Array Creation

NumPy arrays are the core of the library. They can be created in several ways.

In [12]:
# From a Python list or tuple
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
c = np.array((2,4,6,8))

print("1D array:", a)
print("2D array:\n", b)
print("Tupples array\n", c)
# Arrays filled with zeros or ones
zeros_array = np.zeros((2, 3)) # 2x3 array of zeros
ones_array = np.ones((3, 2))  # 3x2 array of ones

print("Zeros array:\n", zeros_array)
print("Ones array:\n", ones_array)

# Array with a constant value
full_array = np.full((2, 2), 7) # 2x2 array filled with 7
print("Full array:\n", full_array)

# Identity matrix
identity_matrix = np.eye(3) # 3x3 identity matrix
print("Identity matrix:\n", identity_matrix)

# Array with a range of numbers
range_array = np.arange(0, 10, 2) # Start, stop (exclusive), step
print("Range array:", range_array)

# Linearly spaced numbers
linspace_array = np.linspace(0, 1, 5) # Start, stop (inclusive), number of points
print("Linspace array:", linspace_array)

# Random arrays
random_uniform = np.random.rand(2, 2) # Uniform distribution [0, 1)
random_normal = np.random.randn(2, 2) # Standard normal distribution
random_int = np.random.randint(0, 10, size=(2, 3)) # Random integers [low, high)

print("Random uniform:\n", random_uniform)
print("Random normal:\n", random_normal)
print("Random integers:\n", random_int)

1D array: [1 2 3]
2D array:
 [[1 2]
 [3 4]]
Tupples array
 [2 4 6 8]
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full array:
 [[7 7]
 [7 7]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Random uniform:
 [[0.18240117 0.8204444 ]
 [0.3419423  0.98188866]]
Random normal:
 [[-0.11511101 -0.32086949]
 [-1.28035502  0.08993626]]
Random integers:
 [[7 7 0]
 [9 2 8]]


#### 3. Array Attributes

Useful properties of a NumPy array.

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape (dimensions):", arr.shape)
print("Number of dimensions (rank):", arr.ndim)
print("Number of elements:", arr.size)
print("Data type of elements:", arr.dtype)
print("Size of each element in bytes:", arr.itemsize)
print("Total size in bytes:", arr.nbytes)

Array:
 [[1 2 3]
 [4 5 6]]
Shape (dimensions): (2, 3)
Number of dimensions (rank): 2
Number of elements: 6
Data type of elements: int64
Size of each element in bytes: 8
Total size in bytes: 48


#### 4. Basic Operations

Element-wise operations, aggregations, and universal functions.

In [4]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Element-wise addition, subtraction, multiplication, division
print("Addition (a+b):", a + b)
print("Subtraction (a-b):", a - b)
print("Multiplication (a*b):", a * b)
print("Division (a/b):", a / b)

# Exponentiation
print("Exponentiation (a**2):", a ** 2)

# Comparison operators (element-wise)
print("Comparison (a > 20):", a > 20)

# Universal functions (ufuncs)
print("Square root (np.sqrt(a)):", np.sqrt(a))
print("Sine (np.sin(a)):", np.sin(a))
print("Exponential (np.exp(a)):", np.exp(a))

Addition (a+b): [11 22 33 44]
Subtraction (a-b): [ 9 18 27 36]
Multiplication (a*b): [ 10  40  90 160]
Division (a/b): [10. 10. 10. 10.]
Exponentiation (a**2): [ 100  400  900 1600]
Comparison (a > 20): [False False  True  True]
Square root (np.sqrt(a)): [3.16227766 4.47213595 5.47722558 6.32455532]
Sine (np.sin(a)): [-0.54402111  0.91294525 -0.98803162  0.74511316]
Exponential (np.exp(a)): [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]


#### 5. Aggregation Functions

Calculating statistics over arrays.

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Sum of all elements:", arr.sum())
print("Minimum of all elements:", arr.min())
print("Maximum of all elements:", arr.max())
print("Mean of all elements:", arr.mean())
print("Standard deviation of all elements:", arr.std())

# Aggregation along an axis (0 for columns, 1 for rows)
print("Sum along columns (axis=0):", arr.sum(axis=0))
print("Mean along rows (axis=1):", arr.mean(axis=1))

Array:
 [[1 2 3]
 [4 5 6]]
Sum of all elements: 21
Minimum of all elements: 1
Maximum of all elements: 6
Mean of all elements: 3.5
Standard deviation of all elements: 1.707825127659933
Sum along columns (axis=0): [5 7 9]
Mean along rows (axis=1): [2. 5.]


#### 6. Indexing and Slicing

Accessing specific elements or subarrays.

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1D Array:", arr)

# Accessing elements
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing (start:stop:step)
print("Elements from index 2 to 5 (exclusive):", arr[2:5])
print("Elements from beginning to index 4 (exclusive):", arr[:4])
print("Elements from index 6 to end:", arr[6:])
print("Every other element:", arr[::2])
print("Reversed array:", arr[::-1])

# 2D Array Indexing
arr_2d = np.array([[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]])
print("\n2D Array:\n", arr_2d)

# Accessing a single element (row, column)
print("Element at (0, 1):", arr_2d[0, 1])

# Accessing a row
print("First row:", arr_2d[0, :])
print("First row (alternative):", arr_2d[0])

# Accessing a column
print("Second column:", arr_2d[:, 1])

# Slicing rows and columns
print("Subset (rows 0-1, cols 1-2):\n", arr_2d[0:2, 1:3])

# Boolean indexing
print("Elements greater than 14:\n", arr_2d[arr_2d > 14])

# Fancy indexing
print("Elements at specific indices (0,0), (1,2), (2,1):", arr_2d[[0, 1, 2], [0, 2, 1]])

1D Array: [1 2 3 4 5 6 7 8 9]
First element: 1
Last element: 9
Elements from index 2 to 5 (exclusive): [3 4 5]
Elements from beginning to index 4 (exclusive): [1 2 3 4]
Elements from index 6 to end: [7 8 9]
Every other element: [1 3 5 7 9]
Reversed array: [9 8 7 6 5 4 3 2 1]

2D Array:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Element at (0, 1): 11
First row: [10 11 12]
First row (alternative): [10 11 12]
Second column: [11 14 17]
Subset (rows 0-1, cols 1-2):
 [[11 12]
 [14 15]]
Elements greater than 14:
 [15 16 17 18]
Elements at specific indices (0,0), (1,2), (2,1): [10 15 17]


#### 7. Array Manipulation

Reshaping, joining, and splitting arrays.

In [7]:
arr = np.arange(9)
print("Original 1D array:", arr)

# Reshaping
reshaped_arr = arr.reshape((3, 3))
print("Reshaped to 3x3:\n", reshaped_arr)

# Flattening
flattened_arr = reshaped_arr.flatten()
print("Flattened array:", flattened_arr)

# Transpose
print("Transposed array:\n", reshaped_arr.T)

# Concatenation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Concatenated (horizontal):", np.concatenate((a, b)))

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Vertical stack:\n", np.vstack((arr1, arr2)))
print("Horizontal stack:\n", np.hstack((arr1, arr2)))

# Splitting
split_arr = np.array([1, 2, 3, 4, 5, 6])
print("Original for splitting:", split_arr)
print("Split into 3 equal arrays:", np.array_split(split_arr, 3))

arr_to_split_2d = np.arange(12).reshape((3, 4))
print("\n2D array for splitting:\n", arr_to_split_2d)
print("Horizontal split (columns):\n", np.hsplit(arr_to_split_2d, 2))
print("Vertical split (rows):\n", np.vsplit(arr_to_split_2d, 3))

Original 1D array: [0 1 2 3 4 5 6 7 8]
Reshaped to 3x3:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Flattened array: [0 1 2 3 4 5 6 7 8]
Transposed array:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
Concatenated (horizontal): [1 2 3 4 5 6]
Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]
Original for splitting: [1 2 3 4 5 6]
Split into 3 equal arrays: [array([1, 2]), array([3, 4]), array([5, 6])]

2D array for splitting:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Horizontal split (columns):
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
Vertical split (rows):
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


#### 8. Linear Algebra

Basic linear algebra operations.

In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", a)
print("Matrix B:\n", b)

# Dot product (matrix multiplication)
print("Dot product (A @ B):\n", a @ b)
print("Dot product (np.dot(A, B)):\n", np.dot(a, b))

# Inverse of a matrix
inv_a = np.linalg.inv(a)
print("Inverse of A:\n", inv_a)

# Determinant of a matrix
det_a = np.linalg.det(a)
print("Determinant of A:", det_a)

# Eigenvalues and eigenvectors
# eigenvalues, eigenvectors = np.linalg.eig(a)
# print("Eigenvalues:", eigenvalues)
# print("Eigenvectors:\n", eigenvectors)

# Solve a linear system Ax = b
A = np.array([[2, 1], [1, -1]])
b_vec = np.array([4, 1])
x = np.linalg.solve(A, b_vec)
print("Solution to Ax=b:", x)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Dot product (A @ B):
 [[19 22]
 [43 50]]
Dot product (np.dot(A, B)):
 [[19 22]
 [43 50]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
Solution to Ax=b: [1.66666667 0.66666667]
